### ISSUE TITLE
Bio of principal contact author displayed for all authors

### ISSUE THREAD

**Issue by amandastevens** [pkp/classic#18]
To view an author's bio, on the article page you can click "More info" and then "Bio" below each author's name.  However, when there is more than one author for an article and each author has a different bio, the first author's bio is shown for every author.  See as an example https://demo.publicknowledgeproject.org/ojs3/demo/index.php/classic/article/view/818 

I tested this on 2 sites using the Classic theme. It does not occur on a site using the same version of OJS and the Bootstrap theme, so I think it's a theme issue.

**Comment by Vitaliy-1** [comment]
Thanks!
Should be fixed with this commit. Let me know if it's not resolved
