### ISSUE TITLE
Extra comma in the issue title when volume not set to display

### ISSUE THREAD

**Issue by israelcefrin** [pkp/classic#20]
When setting issue title to not show the "volume" info, there will be a comma as a first character showing up in the issue title.
To reproduce this issue:

Issues > Back Issues > Edit issue > Issue Data > uncheck "Volume"

![deepinscreenshot_select-area_20190308160948](https://user-images.githubusercontent.com/4992902/54049904-a4707000-41bc-11e9-862c-444d4f061d97.png)

**Comment by Vitaliy-1** [comment]
Thanks! Fixed.
