### ISSUE TITLE
Empty page when Classic theme activated

### ISSUE THREAD

**Issue by romanomsandra** [pkp/classic#21]
Hi there!

I have been able to install and activate the Classic theme 1.0.0-2 in OJS 3.1.2, but it gives a completely blank page when the website is loaded. 

I've tried also to install the 1.0.0 version of the theme, but it cracks the complete system.

What I am doing wrong?

Any help appreciated, many thanks.

**Comment by Vitaliy-1** [comment]
In OJS 3.1.2 major changes regarding templates were introduced, so previous versions will not work there. I'm working on a new release, most probably it will be ready at the start of the next week.

**Comment by romanomsandra** [comment]
Oh, great, then. I'll wait for the new release.
Thanks a lot!
