### ISSUE TITLE
No linking back to issue ToC from an article summary page

### ISSUE THREAD

**Issue by RewindLife** [pkp/classic#30]
When on an article summary page, there is no link to go to the issue ToC (of which the artile is part of). Perhaps the volume, number text line at the top of the article summary page should be linked to the issue.

**Comment by sssoz** [comment]
I’ve added a simple link, but I think we can do better and provide a much better-looking and more clear link back to the article to which an article belongs. Apologies for the delay in responding to this issues. 

See PR https://github.com/pkp/classic/pull/40
