### ISSUE TITLE
Display homepage image

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/classic#32]
Right now it's not implemented for the Classic theme. @sssoz do you think it's worth to add it?

**Comment by AhemNason** [comment]
Speaking from the perspective of someone who works with hosted journals a lot, I feel like integrating a homepage image in the same way (or similar to) that Immersion handles it would make the classic theme a little stronger in terms of flexibility. Just a quick 2 cents.

**Comment by sssoz** [comment]
Agreed, I do feel that Classic has fewer personalisation options, and a homepage image would greatly benefit this theme. Assigning this to myself.
