### ISSUE TITLE
Child theme not fetching parent theme templates

### ISSUE THREAD

**Issue by israelcefrin** [pkp/classic#33]
Hi

I was working in a child theme from the Classic Theme, but apparently the child one was not fetching the 'templates" from its parent. 
I had to copy the whole templates folder to make it work. Does this theme have some restriction to child themes? 

Now with this folder the CSS is fetch from the parent theme folder without any issue.

Cheers

**Comment by Vitaliy-1** [comment]
Hi Israel,

This is a general problem. Take a look at [this issue](https://github.com/pkp/pkp-lib/issues/4054), I've made PRs there, the last one, which is merged, should fix it.

**Comment by sssoz** [comment]
This seems to be the same issue as #16 - if so, let’s close this one, as there seems to be more info on the older issue.

**Comment by Vitaliy-1** [comment]
The fix was shipped to OJS 3.1.2 and master
