### ISSUE TITLE
Announcements are missing from the homepage

### ISSUE THREAD

**Issue by RewindLife** [pkp/classic#51]
It seems that active announcements are missing from the homepage. Even though the setting "Display ___ of the most recent announcements on the journal homepage" is enabled in Settings > Website > Announcements, the announcements block is still missing. In comparison, the Manuscript Theme does display it. 

Is this omission by design or a bug? Can it be added/fixed?
(We are using Classic Theme version 1.0.1)
Thanks.

**Comment by Vitaliy-1** [comment]
Hi @RewindLife,

Are you using the latest version of the plugin? It should contain this feature.

**Comment by Vitaliy-1** [comment]
Sorry, you specified the version. Try to update to 1.0.2.
