### ISSUE TITLE
Avoid logo yellow highlight when hovered

### ISSUE THREAD

**Issue by leonardomancini87** [pkp/classic#54]
Hi there,
I hope this could result useful also to others using the Classic theme (I am currently using the latest 1.02 on ojs 3.1.2-4).
I have noticed a strange behavior of the website on the logo when I decide to use a image as a logo in substitution to plain text. I know that it is generally suggested to prefer the text, for the mobile version of the website, but somehow I really need to upload an image because it is one of the elements which most give the “identity” of the journal. I will try to upload an image as a logo which could fit in any device.
So, the strange behavior is that when I pass with the mouse over the logo-image, it gets a yellow stripe on it, as if it was a normal link. I attach hereby a screenshot which shows the situation I am trying to describe. I have tried to “detect” the css code which regulates this behavior, but, if I am not wrong, it relies also on all the links. So if I delete if for the logo, it will also affect the normal style behavior of all links, which is something I would like to avoid. In any case, this would be the relevant code if I am not wrong, in the css:

a:hover, a:active, a:focus {
color: #000;
text-decoration: none;
background-color: #ffd120;
}

Does somebody know how could I overcome this problem, avoiding the yellow strip to show up if I use a logo as an image and when I try to go over it with the mouse?
I would be really helpful to anyone willing to the help me on this.
Best regards
Leonardo

Link in the forum: https://forum.pkp.sfu.ca/t/classic-theme-avoid-logo-yellow-highlight-when-hovered/57843/4
<img width="1440" alt="7de04d6c0c8b6efc7fc4fdcb1b99b5664320edd9" src="https://user-images.githubusercontent.com/59882995/72356699-f857b980-36e9-11ea-9d6a-7e51c42504fc.png">

**Comment by Vitaliy-1** [comment]
Thanks!

**Comment by leonardomancini87** [comment]
Vitaly I didn't solve the issue! It is still unfixed!

**Comment by Vitaliy-1** [comment]
Are you using git and master branch? In this case, don't forget to pull the latest changes.
If you already applied the commit, clear the cache. 
Let me know if wouldn't help.

**Comment by leonardomancini87** [comment]
Oh sorry, I am very new to the functioning of "Git Hub". Actually I installed the them through Ftp simply, so not using GitHub. Is there a way to take the new solution in any case?
Thank you very much for your time and attention.

**Comment by Vitaliy-1** [comment]
If using git directly, you'll need to install it first on your server. Usually, it's not possible with shared hosting. Another option could be to install git on your local machine, clone the repository, delete the theme on a server and upload this one through ftp.
Git installation: https://git-scm.com/downloads
Git is a command-line tool, thus you'll need to write from a CMD (on windows) or terminal (linux/MacOS): `git clone https://github.com/pkp/classic`. It will upload the master branch in your current directory. When update, just enter the folder (cd path/to/the/theme/classic) and `git pull`. Usually, the master branch is quite stable, although I cannot guarantee it.

If you never worked with the command-line before, you can just download a zip archive from the current master branch and unpack it manually to your local machine, then upload unpacked files on the server.
