### ISSUE TITLE
Article page: ORCID image inherits link styling

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/classic#55]
See: https://forum.pkp.sfu.ca/t/classic-theme-avoid-orcid-icon-to-be-underlined-and-stick-to-the-the-authors-name/58168

**Comment by leonardomancini87** [comment]
Dear @Vitaliy-1, 
thank you very much for your support.
Since I can only apply the custom.css code, do you know if I could add some, in order to apply this fix? 
With my best regards,
Leonardo

**Comment by Vitaliy-1** [comment]
https://github.com/pkp/classic/commit/0249acecf5be3ff6e4acc64869fee15b5bfe0d0c
