### ISSUE TITLE
Change the color of section titles to dark grey

### ISSUE THREAD

**Issue by NateWr** [pkp/classic#6]
Moved from https://github.com/Vitaliy-1/classic/issues/60

> @sssoz Can you specify this one. Section title color is @warm-grey (#757575) and issue title @gunmetal (#4d6066). Should these 2 elements be in one color?

**Comment by sssoz** [comment]
Closing, it’s been resolved in the following commit: https://github.com/pkp/classic/pull/37/commits/241aeb538fb2d8dd0fff2a3a4a0bd88cb65919fd

All mentions of the `@gunmetal` colour variable have been removed; they were included in error, possibly during the mockup to Zeplin style guide stage a long time ago. `@gunmetal` was meant to be the same as a dark grey. Variables for greys have been cleaned up.
