### ISSUE TITLE
Mising string in Classic on OJS 3.2.

### ISSUE THREAD

**Issue by marcbria** [pkp/classic#65]
**Describe the bug**
##manager.setup.journalSummary## is not defined in en_ES with Classic theme.

**To Reproduce**
1. Enable Classic theme.
2. Go to Appearance.
3. Scroll down.

**Expected behavior**
A translated string.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/2779168/76205603-da469b00-61fa-11ea-9645-f45e6993eaa7.png)

**Desktop (please complete the following information):**
 - OS: Alpine
 - Browser: Firefox.
 - Version: Dockerized OJS 3.2 over apache + php 7.3

**Additional context**
It works fine in other langs (ie: es_ES).

Nate comment this on Slack "Looks like this was renamed manager.setup.contextSummary".

**Comment by asmecher** [comment]
@marcbria, is `en_ES` intentional or is that a typo?

**Comment by marcbria** [comment]
Typo. :-(

**Comment by asmecher** [comment]
Changed `manager.setup.journalSummary` to `manager.setup.contextSummary` to match renamed key in OJS.
