### ISSUE TITLE
Improve theme description

### ISSUE THREAD

**Issue by NateWr** [pkp/classic#7]
Can we improve the theme description in the locale files?

https://github.com/pkp/classic/blob/master/locale/en_US/locale.xml#L7

This is the description that people will see when browsing the list of themes in the plugin gallery, so something to distinguish this from other themes will be good. :+1:

**Comment by Vitaliy-1** [comment]
@sssoz Can you look at this one? I believe, that you already have got a good description of this theme.

**Comment by kaitlinnewson** [comment]
Resolved in https://github.com/pkp/classic/commit/da55d7b5a32f8c90a72a223f26620a83e11a1d0b.
