### ISSUE TITLE
More Citation Formats button doesn't have enough contrast

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/classic#76]
1. With white color is chosen as primary the button doesn't have an outline that distinguishes it from the other text:
(tested on a current master branch)
![screencapture-localhost-8000-index-php-psp-article-view-162-2020-06-17-19_51_07](https://user-images.githubusercontent.com/20665587/84926388-fb5d3880-b0d3-11ea-8efd-f9d3098e2db2.png)
2. When black color is chosen as a primary the text inside the button is indistinguishable from the black background:
![screencapture-localhost-8000-index-php-psp-article-view-196-2020-06-17-19_53_57](https://user-images.githubusercontent.com/20665587/84926616-52630d80-b0d4-11ea-931f-b64fa884a6e2.png)

**Comment by Vitaliy-1** [comment]
@sssoz, can you take a look at this one?

**Comment by Vitaliy-1** [comment]
Still text color is indistinguishable from a background when primary color is black:
![screencapture-localhost-8000-index-php-psp-article-view-159-2020-06-19-12_02_50](https://user-images.githubusercontent.com/20665587/85115834-fd82dc80-b224-11ea-89f4-bd79593eb765.png)

**Comment by kaitlinnewson** [comment]
Confirmed resolved in 3.3/3.4, closing.
