### ISSUE TITLE
Plugin Upgrade Error

### ISSUE THREAD

**Issue by vinitkumargunjan** [pkp/classic#81]
**Describe the bug**
When I am uploading the tar file I get the error message as files of this type cannot be uploaded. Additionally when I am trying to upgrade from list of plugins I get error with notification "null"

**Expected behavior**
It should be installed/upgraded

**Screenshots**
![Screenshot 2020-06-25 at 5 48 24 PM](https://user-images.githubusercontent.com/18115487/85718765-70e88a80-b70c-11ea-9af6-18516f66de1a.png)

**Desktop (please complete the following information):**
 - OS: 10.15.5 macOS Catalina

**Additional context**
Na

**Comment by asmecher** [comment]
@vinitkumargunjan, the support forum is a better place to get general support. I'd suggest starting with this thread: https://forum.pkp.sfu.ca/t/plugin-issue-after-upgradation-of-3-2-03-to-3-2-1-0/61358
