### ISSUE TITLE
Copyright not showing

### ISSUE THREAD

**Issue by marlara** [pkp/classic#99]
**Describe the bug**
The copyroght notice is not showing in the article page, just the license. I saw in the preview that there is a modal for the Copyright notice (https://demo.publicknowledgeproject.org/ojs3/demo/index.php/classic/article/view/814) but it doesn't appear in my installation which is ojs 3.3.0.11

![Schermata da 2022-07-07 12-15-31](https://user-images.githubusercontent.com/12834687/177750649-4a2094a7-d214-4121-a6e4-9bf8b25eee3d.png)

I have set the copyright notice in the general settings, not for each articles, but the license is been applied correctly.

![Schermata da 2022-07-07 12-17-23](https://user-images.githubusercontent.com/12834687/177750878-406150a5-8c88-45b3-b4f4-92ff937464b5.png)

**Comment by marlara** [comment]
I think this is because I changed the copyright notice after publishing the article. So not a bug actually, I just need to set up the new copyright notice for each articles I guess?

**Comment by asmecher** [comment]
Hi @marlara -- this is intended behaviour, as changing the journal's copyright/license/etc. shouldn't affect previous submissions. However, if you go to Tools > Permissions, there is a button to reset permissions for all content.

**Comment by marlara** [comment]
Yes I noticed after! Thank you

Il sab 9 lug 2022, 01:17 Alec Smecher ***@***.***> ha scritto:
